project:
 type: website
 output-dir: docs # cambiar carpeta donde se construye el sitio
 
website:
  description: "Portfolio - JP"
  site-url: https://jeronimopennini.github.io/PORTFOLIO_JP/
  title: "Portfolio - JP"
  navbar:
    left:
      - presentacion.qmd
    right:
      - about.qmd
      - curriculum.qmd
      - icon: github
        href: https://github.com/JeronimoPennini
      - icon: linkedin
        href: https://www.linkedin.com/in/jeronimo-pennini
format:
  html:
    code-fold: true
    code-tools: true
    theme:
      - minty
      - brand
      - tema.scss
    css: styles.css



